# Profile section
profile:
  first_name: Kevin
  last_name: Wilczynski
  picture: static/img/me.jpg  # Local picture
  contact:
    address_one: Santa Clarita
    address_two: CA 
    phone: (661) 433-8518
  email: kevinawilczynski@gmail.com
  description: |
    Im a software engineer with a few startups under my belt. Still need to fill in the rest but this is just filler.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# Social section
social:
  github: https://github.com/sirwilly1
  twitter: https://twitter.com/kdogew
  linkedin: https://www.linkedin.com/in/kevin-wilczynski-65083862/
  facebook: https://www.facebook.com/kevin.wilczynski.5/
  website: none

# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - github
  - google
  - slack
  - discord
  - apple
  - linux
  - raspberry-pi

extra_skills:
  - Programming/Languages; Python, C/C++, Java, Javascript, MySQL; HTML;
  - Web scraping 
  - ROS(Robot Operating System)
  - APIs and web development, Flask
  - Image processing and computer vision(OpenCV)
  - Machine learning and deep learning
  - Several Python packages - Flask, NumPy, TensorFlow, OpenCV


# Experience section
experience:
  item7:
    position: Software Engineer
    company: Neutron shipping(Startup)
    from: April 2017
    to: March 2019
    description: >
      Lead programmer for image processing using OpenCV and Intel RealSence
  item6:
    position: Software Engineer
    company: GeoFriends(Startup)
    from: January 2015
    to: February 2016
    description: >
      Head programmer for Geo location based social media platform 
      
  item5:
    position: Software Engineer
    company: ARCS(JPL)
    from: August 2018
    to: August 2021
    description: >
      Head programmer for the Autonomy Research Center for STEAHM (ARCS). Worked with Husky UGV Outdoor Field Research Robot from Clearpath Robotics and development  mapping techniques for navigation systems using LIDAR and Intel RealSence
  item4:
    position: Lead programmer
    company: Rock-SatX
    from: July 2015
    to: September 2018
    description: >
      Programmed communication system to upload with the iridium satellite network to offload the data before impact. Programmed probes mission critical systems, which included integration with NASA’s sounding rocket data lines,activation of probes deployment motors, and activation of servo locks to deploy autorotation fins.
  item3:
    position: Student Researcher
    company: College of the Canyons
    from: May 2015
    to: July 2018
    description: >
      Programmer for High Altitude Space Program (HASP).Worked on flight systems which included activation of onboard heating elements to keep components at optimal temperature. Worked on post-flight data modeling and cleaning.
    
  

# Education section
education:
  item1:
    institution: California State University, Northridge (CSUN)
    program: College of Computer Science
    description: Recived my Bachelor in Computer Science with an emphasis on machine learning 
    from: August 2018
    to: August 2021
  item2:
    institution: College of the Canyons
    program: AA of Computer science 
    description: Majored in Computer Science with an emphasis on Data cleaning.
    from: August 2016
    to: February 2018

# Community section:
community:
  item0:
    institution: kink
    program: kink stuff
    description: "did things , filler filller filler."
    from: September 2019
    to: Present
  item1:
    institution: work
    program: work stuff
    description: "did things , filler filller filler."
    from: September 2019
    to: Present
  item2:
    institution: fun
    program: fun stuff
    description: "did things , filler filller filler."
    from: September 2019
    to: Present




